services:
  app:
    build: .
    container_name: java_app
    image: pee-iptracer:1.0.0
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/iptracerdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_REDIS_HOST=redis
    networks:
      - backend

  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: iptracerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    command: redis-server --appendonly yes

networks:
  backend: